#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-XML-RSS
Version  : 1.60
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-RSS-1.60.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-RSS-1.60.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libx/libxml-feed-perl/libxml-feed-perl_0.53+dfsg-1.debian.tar.xz
Summary  : 'creates and updates RSS files'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0 GPL-2.0
Requires: perl-XML-RSS-license
Requires: perl-XML-RSS-man
Requires: perl(DateTime::Format::Mail)
Requires: perl(DateTime::Format::W3CDTF)
Requires: perl(HTML::Entities)
Requires: perl(Module::Build)
Requires: perl(XML::Parser)
BuildRequires : perl(DateTime::Format::Mail)
BuildRequires : perl(DateTime::Format::W3CDTF)
BuildRequires : perl(HTML::Entities)
BuildRequires : perl(Module::Build)
BuildRequires : perl(XML::Parser)

%description
All rights reserved.
This package is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

%package license
Summary: license components for the perl-XML-RSS package.
Group: Default

%description license
license components for the perl-XML-RSS package.


%package man
Summary: man components for the perl-XML-RSS package.
Group: Default

%description man
man components for the perl-XML-RSS package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n XML-RSS-1.60
mkdir -p %{_topdir}/BUILD/XML-RSS-1.60/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/XML-RSS-1.60/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-XML-RSS
cp LICENSE %{buildroot}/usr/share/doc/perl-XML-RSS/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-XML-RSS/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/XML/RSS.pm
/usr/lib/perl5/site_perl/5.26.1/XML/RSS/Private/Output/Base.pm
/usr/lib/perl5/site_perl/5.26.1/XML/RSS/Private/Output/Roles/ImageDims.pm
/usr/lib/perl5/site_perl/5.26.1/XML/RSS/Private/Output/Roles/ModulesElems.pm
/usr/lib/perl5/site_perl/5.26.1/XML/RSS/Private/Output/V0_9.pm
/usr/lib/perl5/site_perl/5.26.1/XML/RSS/Private/Output/V0_91.pm
/usr/lib/perl5/site_perl/5.26.1/XML/RSS/Private/Output/V1_0.pm
/usr/lib/perl5/site_perl/5.26.1/XML/RSS/Private/Output/V2_0.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-XML-RSS/LICENSE
/usr/share/doc/perl-XML-RSS/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/XML::RSS.3
/usr/share/man/man3/XML::RSS::Private::Output::Base.3
/usr/share/man/man3/XML::RSS::Private::Output::Roles::ImageDims.3
/usr/share/man/man3/XML::RSS::Private::Output::Roles::ModulesElems.3
/usr/share/man/man3/XML::RSS::Private::Output::V0_9.3
/usr/share/man/man3/XML::RSS::Private::Output::V0_91.3
/usr/share/man/man3/XML::RSS::Private::Output::V1_0.3
/usr/share/man/man3/XML::RSS::Private::Output::V2_0.3
